import React, { useState } from 'react';
import { useId } from 'react-id-generator';

// `useId` is a hook that can be used to generate a unique identifier. In this example, we can use `useId` to generate a unique id for a button element that increments the counter when clicked.


// In this example, we use `useState` to manage the state of the counter, and define a `buttonId` variable using `useId` to generate a unique id for the button element that increments the counter when clicked.

// We then define a `handleClick` function that updates the counter using `setCount` when the button is clicked.

// Finally, we render the `count` value in a paragraph element and a button element with a unique `id` attribute generated by `useId`.


function UseIdExample() {
    const [count, setCount] = useState(0);
    const [buttonId] = useId();

    function handleClick() {
        setCount(prevCount => prevCount + 1);
    }

    return (
        <div>
            <p>Count: {count}</p>
            <button id={buttonId} onClick={handleClick}>
                Increment
            </button>
        </div>
    );
}

export default UseIdExample;
