import React, { useState, useId } from 'react';
import Button from '@mui/material/Button';
import Typography from '@mui/material/Typography';
import Card from '@mui/material/Card';


function UseIdExample() {
    const [count, setCount] = useState(0);
    const [buttonId] = useId();

    function handleClick() {
        setCount(prevCount => prevCount + 1);
    }

    return (
        <Card variant="outlined"
            sx={{
                p: 2,
                m: 2,
            }}
        >
            <Typography variant='h6'
                sx={{
                    mb: 2,
                }}
            >UseId</Typography>
            <Typography variant="body1">
                `useId` is a hook that can be used to generate a unique identifier. In this example, we can use `useId` to generate a unique id for a button element that increments the counter when clicked.
                {'\n'}{'\n'}
                In this example, we use `useState` to manage the state of the counter, and define a `buttonId` variable using `useId` to generate a unique id for the button element that increments the counter when clicked.
                We then define a `handleClick` function that updates the counter using `setCount` when the button is clicked.
                {'\n'}{'\n'}
                Finally, we render the `count` value in a paragraph element and a button element with a unique `id` attribute generated by `useId`.
            </Typography>
            <Typography>Count: {count}</Typography>
            <Button id={buttonId} variant="contained" color="primary" onClick={handleClick}>
                Increment
            </Button>
        </Card>
    );
}

export default UseIdExample;
